language: php

php:
  - 7.1.9
  
before_install:
  - echo pwd
  - echo "Downloading phpMyAdmin"
  - wget https://files.phpmyadmin.net/phpMyAdmin/4.9.0.1/phpMyAdmin-4.9.0.1-all-languages.zip
  - echo "Unzipping phpMyAdmin"
  - unzip phpMyAdmin-4.9.0.1-all-languages.zip
  - echo "Renaming phpMyAdmin"
  - mv phpMyAdmin-4.9.0.1-all-languages phpMyAdmin

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"  
  app: "dts-manager"
  env: "DtsManager-dev"
  bucket_name: "dts-manager-s3-bucket"
