dependencies:
    pre:
        - sudo apt-get update
        - sudo apt-get install python-dev
        - sudo pip install awsebcli

workflows:
    version: 2
        jobs:
            - commands:
                - bash ./setup-eb.sh
                - eb deploy

---
version: 2.1

workflows:
    version: 2
    # On master push workflow
    dev-release:
        jobs:
            - commands:
                - bash ./setup-eb.sh
                - eb deploy