---
version: 2.1
    
dependencies:
    pre:
        - sudo apt-get update
        - sudo apt-get install python-dev
        - sudo pip install awsebcli

jobs:
    prod-deploy:
        branch: master
        steps:
            - run:
                command: |
                    bash ./setup-eb.sh
                    eb deploy
