dependencies:
    pre:
        - sudo apt-get update
        - sudo apt-get install python-dev
        - sudo pip install awsebcli
    
deployment:
    production:
        branch: master
        commands:
            - bash ./setup-eb.sh
            - eb deploy