---
version: 2.1
    
dependencies:
    pre:
        - sudo apt-get update
        - sudo apt-get install python-dev
        - sudo pip install awsebcli

jobs:
    build:
        docker: 
            - image: circleci/php:7.4.3-fpm-buster
        steps:
            - checkout
            - bash echo pwd
            - bash ./setup-eb.sh
            - eb deploy
