---
version: 2.1

dependencies:
    pre:
        - sudo apt-get update
        - sudo apt-get install apt-utils
        - sudo apt-get install python3-pip
        - sudo pip install awsebcli

jobs:
    build:
        docker:
            - image: circleci/php:8.0
        steps:
            - checkout
            - run:
                command: |
                    sudo apt-get update
                    sudo apt-get install apt-utils
                    sudo apt-get install python3-pip
                    sudo pip3 install awsebcli
                    ./setup-eb.sh
                    eb deploy
